name: Atualizar Idade

on:
  push:
    branches:
      - main

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Update README
        run: python main.py

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "sofiaeducruz@gmail.com"
          git config --local user.name "Sofia Eduarda"
          git add README.md
          git commit -m "Atualizar idade" -a
          git push
